<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_gridcell_1</name>
   <tag></tag>
   <elementGuidId>f8a90923-83b2-4f91-91cd-ec392cec416a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_even ') and (position() = 2)]//*[(@role = 'gridcell') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ht__row_even:nth-child(2) [role=&quot;gridcell&quot;]:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e83f0eb0-2c79-4733-b113-2ecc1998b857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[98%] h-full z-10</value>
      <webElementGuid>72321f80-e875-424c-bc4f-56c387868e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c005948a-a93b-4c20-b6b0-dbda694c810d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>0b025200-8015-452a-8792-21943ab0a352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>63c36f5b-5b6f-437d-a92f-f9b20d39e929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d907b58f0dff26e7687118fbba0d87b0</value>
      <webElementGuid>5d8e69af-fbfd-4675-821c-d98d3f09be98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_even ') and (position() = 2)]//*[(@role = 'gridcell') and (position() = 2)]</value>
      <webElementGuid>b48758e5-b840-4dc6-8de1-787db1aa36d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_even ') and (position() = 2)]//*[(@role = 'gridcell') and (position() = 2)]</value>
      <webElementGuid>1cf80499-6106-4bfc-9aa2-a96985267368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
