<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_gridcell_2</name>
   <tag></tag>
   <elementGuidId>c03fbfd7-e4ee-4e95-aff4-f7b0f56e867c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_even ') and (position() = 2)]//*[(@role = 'gridcell') and (position() = 3)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ht__row_even:nth-child(2) [role=&quot;gridcell&quot;]:nth-child(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b9fe353a-ed30-4806-83b0-14c8027d3f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[98%] h-full z-10</value>
      <webElementGuid>da164b7c-c3ce-4b15-b323-cfacfd4d1ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e8c38d6b-3085-4602-8199-4161326b4596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>9f5acce3-37c7-48b9-b1aa-790544927fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ea4e3ce0-fb06-4cd0-a23e-570e18374672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-64f172b48e2e4b4c9b26bede787703cd</value>
      <webElementGuid>0dce0b53-657e-4e59-bba0-11c5d9fda47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_even ') and (position() = 2)]//*[(@role = 'gridcell') and (position() = 3)]</value>
      <webElementGuid>f7417842-a143-4552-b99d-f13fa35fa1f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_even ') and (position() = 2)]//*[(@role = 'gridcell') and (position() = 3)]</value>
      <webElementGuid>29ae5ce4-3972-4f07-95a8-a2b515b29952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
