<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_gridcell</name>
   <tag></tag>
   <elementGuidId>b1663d71-259a-4b97-aa69-44dd98ee427d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_odd ') and (position() = 1)]//*[(@role = 'gridcell') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.ht__row_odd:nth-child(1) [role=&quot;gridcell&quot;]:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e1a50018-83e1-4e4e-bf50-6bca30e49515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[98%] h-full z-10</value>
      <webElementGuid>d8e04c2f-790f-485a-b04f-a66c1c1884bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0dfc2ad5-cd1b-4b9e-83fb-8dd0c87fb49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>99664ace-4a7f-4729-8be6-c722f9de6644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>00fb6ecf-1546-4fd6-9877-2e24fefd3ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2167ae7b67ab3f28cc59fda8d236ba41</value>
      <webElementGuid>95065d09-1ced-49af-940c-58cb765d80e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_odd ') and (position() = 1)]//*[(@role = 'gridcell') and (position() = 2)]</value>
      <webElementGuid>9e4e2455-764a-4ed9-916d-642f0f5e0bc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ht__row_odd ') and (position() = 1)]//*[(@role = 'gridcell') and (position() = 2)]</value>
      <webElementGuid>e36cb47c-f992-46ee-8b69-c8efcb417a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
