<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_grapher</name>
   <tag></tag>
   <elementGuidId>cc034dfe-bb73-409e-907b-fb7663eb2eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' border-b ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.border-b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>7efcc5f5-29d8-4f33-8bf0-5b068742ad6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center px-12 py-6 border-b border-white/10</value>
      <webElementGuid>ba5c9b80-9b59-4f6f-b7c0-c32cce239094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>grapher.</value>
      <webElementGuid>955dacd5-9511-499d-842e-48dbceca60e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e74312c11e8b40d3a8419502d17216bd</value>
      <webElementGuid>2fc28c2f-93e1-4662-ba80-376c5618c351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' border-b ')]</value>
      <webElementGuid>1d124b9a-6122-4267-9155-6b5cbb8afcec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' border-b ')]</value>
      <webElementGuid>03d7faf6-d9b8-41d8-bf4c-e5ce14c90978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'grapher.' or . = 'grapher.')]</value>
      <webElementGuid>3fd63c87-18ea-4ad5-9d0c-743cd3060389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
