<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_welcome_back</name>
   <tag></tag>
   <elementGuidId>9cc79656-cd7f-45bb-895d-4c578fe0d008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-2xl.font-semibold.tracking-tight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Welcome back.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5a0df6e5-36ef-45ff-adbd-3d2927477fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-2xl font-semibold tracking-tight</value>
      <webElementGuid>0baab849-fd59-4c31-a43c-08640aedcd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome back.</value>
      <webElementGuid>b919287f-9dc5-4616-9100-0bbe1b11bccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background text-foreground flex flex-col&quot;]/div[@class=&quot;flex justify-between items-center px-12 py-6&quot;]/div[1]/p[@class=&quot;text-2xl font-semibold tracking-tight&quot;]</value>
      <webElementGuid>7fda4301-0c86-4a03-b9a1-703a5eeb7d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/p</value>
      <webElementGuid>fd79e545-2e91-49a6-b7bd-427d1ea7c1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New graph'])[1]/preceding::p[2]</value>
      <webElementGuid>ea78a9f3-d2ca-494d-9b93-861732c3dc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untitled Graph'])[1]/preceding::p[2]</value>
      <webElementGuid>29f78262-7606-489e-858b-5860401027d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome back.']/parent::*</value>
      <webElementGuid>e7a55891-76bb-40bc-b44f-ade7a8260cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>a1899988-b75a-4703-9844-cc8525cafffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Welcome back.' or . = 'Welcome back.')]</value>
      <webElementGuid>41673bc5-0925-4e8e-9e28-3af55701f720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
