<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_</name>
   <tag></tag>
   <elementGuidId>145cf607-7c8a-4931-b478-f5542b3f20db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' datepicker-days ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' next ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.datepicker-days .next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>ef09d0cf-bc41-4f57-a901-a23f7191cca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>c1ce1f3a-8f0e-43ea-b168-138872c8525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>»</value>
      <webElementGuid>716a38f4-da57-4ce8-964f-fbecbcef23a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d1d373c97fc4e10fab1624af17c5ece5</value>
      <webElementGuid>91754d44-5d53-4eb7-8856-2fb00b756e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' datepicker-days ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' next ')]</value>
      <webElementGuid>c6149ec2-077e-45fe-85f7-c227ef0bf248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' datepicker-days ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' next ')]</value>
      <webElementGuid>76343be8-1025-4c91-9a4f-d0f9238d97f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '»' or . = '»')]</value>
      <webElementGuid>faff6f9a-c2d5-41ee-af95-1d725bdab542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
